version: '3.7'
services:
  nodejs:
    build: ./gate-simulator
    ports:
      - '9999:9999'

  postgres:
    image: postgres:12.0-alpine
    container_name: pstg-container
    ports:
      - '5432:5432'

    environment:
      - POSTGRES_RANDOM_ROOT_PASSWORD=yes
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass

  mysql:
    image: mysql:8.0.19
    ports:
      - '3306:3306'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass